// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7bqPq7k6ghwqX_-zfOs48bC8GgOvOIKs',
    appId: '1:870940068476:android:4f2713f081743fd64597f9',
    messagingSenderId: '870940068476',
    projectId: 'educommunity-delit',
    databaseURL: 'https://educommunity-delit.firebaseio.com',
    storageBucket: 'educommunity-delit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQiN58AGa2288-ZX7Dai4fbsySD4819E8',
    appId: '1:870940068476:ios:85a4eeb02cf5dff64597f9',
    messagingSenderId: '870940068476',
    projectId: 'educommunity-delit',
    databaseURL: 'https://educommunity-delit.firebaseio.com',
    storageBucket: 'educommunity-delit.appspot.com',
    androidClientId: '870940068476-9gs8a82lc24ebuo5695pev5qpgu1kc6h.apps.googleusercontent.com',
    iosClientId: '870940068476-4qreu9qmqknlicg2mdn5om3fmbgljvr0.apps.googleusercontent.com',
    iosBundleId: 'com.delit.freeEdu4All',
  );
}
